[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false

[profile.default.metadata]
bytecode_hash = "ipfs"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
anvil = "http://localhost:8545"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
